# Generated by Django 3.2.3 on 2022-02-22 08:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('type_component', models.CharField(max_length=100, verbose_name='Тип компонента')),
                ('marking', models.CharField(max_length=100, unique=True, verbose_name='Маркировка')),
                ('note', models.CharField(blank=True, max_length=100, null=True, verbose_name='Корпус')),
                ('amount_eis', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество ЭИС')),
                ('amount_trk', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество ТРК')),
                ('amount_vts', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество ВТС')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена/шт')),
            ],
            options={
                'verbose_name': 'Компонент',
                'verbose_name_plural': 'Компоненты',
                'ordering': ['type_component'],
            },
        ),
        migrations.CreateModel(
            name='Maker_company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Record_block',
            fields=[
                ('number_block', models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер блока')),
                ('serial_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Заводской_номер')),
                ('date_add', models.DateField(verbose_name='Дата приема')),
                ('date_repair', models.DateField(blank=True, null=True, verbose_name='Дата ремонта')),
                ('date_shipment', models.DateField(blank=True, null=True, verbose_name='Дата отправки')),
                ('FIO', models.CharField(blank=True, max_length=30, null=True, verbose_name='ФИО')),
                ('status', models.CharField(blank=True, choices=[('принят', 'принят'), ('готов', 'готов'), ('выдан', 'выдан'), ('забракован', 'забракован'), ('производителю', 'производителю')], default='принят', max_length=15, null=True, verbose_name='Состояние')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='Примечание')),
                ('passed', models.CharField(blank=True, max_length=25, null=True, verbose_name='Передан ФИО')),
            ],
            options={
                'verbose_name': 'Блок в центре',
                'verbose_name_plural': 'Блоки в центре',
                'ordering': ['-number_block'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50, unique=True, verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ['region'],
            },
        ),
        migrations.CreateModel(
            name='Type_block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_block', models.CharField(max_length=100, unique=True, verbose_name='Наименование блока')),
                ('components', models.ManyToManyField(blank=True, related_name='block_components', to='base.Component', verbose_name='Компоненты блока')),
                ('maker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_maker', to='base.maker_company', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Тип блока',
                'verbose_name_plural': 'Типы блоков',
                'ordering': ['name_block'],
            },
        ),
        migrations.CreateModel(
            name='Record_component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=10, null=True, verbose_name='Компания')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('date_add', models.DateField(auto_now_add=True, verbose_name='Дата учета')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_block', to='base.record_block', verbose_name='Номер блока')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_component', to='base.component', verbose_name='Компонент')),
            ],
            options={
                'verbose_name': 'Учет',
                'verbose_name_plural': 'Учет компонентов',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='record_block',
            name='name_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_type_block', to='base.type_block', verbose_name='Тип блока'),
        ),
        migrations.AddField(
            model_name='record_block',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='base.unit', verbose_name='Подразделение'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='Изображение')),
                ('text', models.TextField(verbose_name='Текст')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество')),
                ('amount_order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Заказано')),
                ('amount_commit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Получено')),
                ('date_created', models.DateField(blank=True, null=True, verbose_name='Дата заявки')),
                ('date_processing', models.DateField(blank=True, null=True, verbose_name='Дата обработки')),
                ('date_order', models.DateField(blank=True, null=True, verbose_name='Дата заказа')),
                ('date_commit', models.DateField(blank=True, null=True, verbose_name='Дата получения')),
                ('delivery_time', models.CharField(blank=True, max_length=15, null=True, verbose_name='Срок поставки')),
                ('provider', models.CharField(blank=True, max_length=100, null=True, verbose_name='Поставщик')),
                ('status', models.CharField(choices=[('ожидает', 'ожидает'), ('обработан', 'обработан'), ('заказан', 'заказан'), ('оплачен', 'оплачен'), ('получен', 'получен'), ('отменен', 'отменен'), ('недопоставка', 'недопоставка')], default='ожидает', max_length=25, null=True, verbose_name='Статус заявки')),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер счета')),
                ('invoice_amount', models.FloatField(blank=True, null=True, verbose_name='Сумма счета')),
                ('payer', models.CharField(blank=True, choices=[('ТРК', 'ТРК'), ('ВТС', 'ВТС'), ('ЭИС', 'ЭИС'), ('--------', '--------')], default='--------', max_length=25, null=True, verbose_name='Плательщик')),
                ('user', models.CharField(blank=True, max_length=180, null=True, verbose_name='ФИО')),
                ('note', models.CharField(blank=True, max_length=100, null=True, verbose_name='Примечание')),
                ('component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='component_request', to='base.component', verbose_name='Наименование компонента')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('number_block', models.PositiveIntegerField(verbose_name='Номер блока')),
                ('name_block', models.CharField(max_length=150, verbose_name='Тип блока')),
                ('serial_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Заводской_номер')),
                ('date_shipment_maker', models.DateField(blank=True, null=True, verbose_name='Дата отправки производителю')),
                ('date_add_maker', models.DateField(blank=True, null=True, verbose_name='Дата возврата')),
                ('maker_status', models.CharField(choices=[('ожидает', 'ожидает'), ('отправлен', 'отправлен'), ('возвращен', 'возвращен'), ('забракован', 'забракован')], default='отправлен', max_length=15, verbose_name='Состояние')),
                ('reason', models.CharField(blank=True, max_length=65, null=True, verbose_name='Причина отправки')),
                ('note_maker', models.CharField(blank=True, max_length=65, null=True, verbose_name='Примечание')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.record_block', verbose_name='Блок')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.maker_company', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Ремон производителя',
                'verbose_name_plural': 'Ремонты Производителей',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Defect_statement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('date_add', models.DateField(verbose_name='Дата')),
                ('defect_1', models.CharField(max_length=100, verbose_name='Неисправность 1')),
                ('defect_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Неисправность 2')),
                ('defect_3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Неисправность 3')),
                ('result', models.CharField(max_length=100, verbose_name='Заключение')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect_block', to='base.record_block', verbose_name='Блок')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_statement', to='base.unit', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Деектная ведомость',
                'verbose_name_plural': 'Дефектные ведомости',
                'ordering': ['block'],
            },
        ),
    ]
