# Generated by Django 3.2.3 on 2021-07-10 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_request', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='record_component',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_block', to='base.record_block', verbose_name='Номер блока'),
        ),
        migrations.AddField(
            model_name='record_component',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_component', to='base.component', verbose_name='Компонент'),
        ),
        migrations.AddField(
            model_name='record_block',
            name='name_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_type_block', to='base.type_block', verbose_name='Тип блока'),
        ),
        migrations.AddField(
            model_name='record_block',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='base.unit', verbose_name='Подразделение'),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='order',
            name='component',
            field=models.ManyToManyField(related_name='order_component', to='base.Request', verbose_name='Компоненты'),
        ),
        migrations.AddField(
            model_name='maker',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.record_block', verbose_name='Блок'),
        ),
        migrations.AddField(
            model_name='maker',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.maker_company'),
        ),
        migrations.AddField(
            model_name='defect_statement',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.record_block', verbose_name='Блок'),
        ),
        migrations.AddField(
            model_name='defect_statement',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_statement', to='base.unit', verbose_name='Подразделение'),
        ),
    ]
