# Generated by Django 3.2.3 on 2021-09-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect_statement',
            name='date_add',
            field=models.DateField(null=True, verbose_name='Дата'),
        ),
    ]
