# Generated by Django 3.2.3 on 2021-05-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_block',
            name='components',
            field=models.ManyToManyField(blank=True, related_name='block_components', to='base.Components', verbose_name='Компоненты блока'),
        ),
    ]
