# Generated by Django 3.2.3 on 2021-09-22 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_defect_statement_date_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect_statement',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect_block', to='base.record_block', verbose_name='Блок'),
        ),
        migrations.AlterField(
            model_name='defect_statement',
            name='date_add',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
