# Generated by Django 3.2.3 on 2021-06-30 17:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210629_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record_component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=10, null=True, verbose_name='Компания')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('date_add', models.DateField(auto_now_add=True, verbose_name='Дата учета')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_block', to='base.record_block', verbose_name='Номер блока')),
            ],
            options={
                'verbose_name': 'Учет',
                'verbose_name_plural': 'Учет компонентов',
                'ordering': ['-id'],
            },
        ),
        migrations.RenameModel(
            old_name='Components',
            new_name='Component',
        ),
        migrations.DeleteModel(
            name='Record_components',
        ),
        migrations.AddField(
            model_name='record_component',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_component', to='base.component', verbose_name='Компонент'),
        ),
    ]
