# Generated by Django 3.2.3 on 2022-02-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20220210_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='maker',
            name='reason',
            field=models.CharField(blank=True, max_length=65, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='maker',
            name='status',
            field=models.CharField(blank=True, choices=[('возвращен', 'возвращен'), ('отправлен', 'отправлен'), ('забракован', 'забракован')], default='отправлен', max_length=15, null=True, verbose_name='Состояние'),
        ),
    ]
