# Generated by Django 3.2.3 on 2021-06-30 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210630_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record_component',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_component', related_query_name='query_record', to='base.component', verbose_name='Компонент'),
        ),
    ]
