# Generated by Django 3.2.3 on 2022-02-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20220210_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='maker',
            name='name_block',
            field=models.CharField(default=1, max_length=150, verbose_name='Тип блока'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maker',
            name='serial_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Заводской_номер'),
        ),
    ]
