# Generated by Django 3.2.3 on 2021-06-30 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_record_component_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='type_block',
            name='maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='block_maker', to='base.maker_company', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='record_component',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_component', to='base.component', verbose_name='Компонент'),
        ),
    ]
