# Generated by Django 3.2.3 on 2022-02-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20220210_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maker',
            name='block',
        ),
        migrations.AddField(
            model_name='maker',
            name='number_block',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер блока'),
            preserve_default=False,
        ),
    ]
