# Generated by Django 3.2.3 on 2022-02-10 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20220210_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maker',
            old_name='note',
            new_name='note_maker',
        ),
    ]
