# Generated by Django 3.2.3 on 2021-07-08 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20210630_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='component',
        ),
        migrations.DeleteModel(
            name='Applications',
        ),
        migrations.DeleteModel(
            name='Applications_status',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
