# Generated by Django 3.2.3 on 2022-02-10 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_note_maker_note_maker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maker',
            old_name='note_maker',
            new_name='note',
        ),
        migrations.AddField(
            model_name='maker',
            name='block',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.record_block', verbose_name='Блок'),
            preserve_default=False,
        ),
    ]
