# Generated by Django 3.2.3 on 2021-07-08 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0009_auto_20210708_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=25, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество')),
                ('created', models.DateField(verbose_name='Дата заявки')),
                ('note', models.CharField(max_length=100, verbose_name='Примечание')),
                ('component', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='component_request', to='base.component', verbose_name='Наименование компонента')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_request', to='base.status_request', verbose_name='Статус заявки')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_request', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created'],
            },
        ),
    ]
