# Generated by Django 3.2.3 on 2021-07-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_request_status_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата заявки'),
        ),
    ]
