# Generated by Django 3.2.3 on 2022-02-10 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_maker_maker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maker',
            old_name='note',
            new_name='note_maker',
        ),
    ]
