# Generated by Django 3.2.3 on 2021-07-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_request_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('ожидает', 'ожидает'), ('обработан', 'готов'), ('получен', 'получен')], default='ожидает', max_length=25, null=True, verbose_name='Статус заявки'),
        ),
        migrations.DeleteModel(
            name='Status_Request',
        ),
    ]
