# Generated by Django 3.2.3 on 2022-02-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_note_maker_note_maker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maker',
            name='maker',
            field=models.CharField(max_length=20, verbose_name='Производитель'),
        ),
    ]
