# Generated by Django 3.2.3 on 2021-07-09 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0012_auto_20210709_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-pk'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('ожидает', 'ожидает'), ('обработан', 'обработан'), ('получен', 'получен')], default='ожидает', max_length=25, null=True, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_request', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
