# Generated by Django 3.2.3 on 2022-02-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_maker_maker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maker',
            old_name='status',
            new_name='maker_status',
        ),
        migrations.AlterField(
            model_name='maker',
            name='reason',
            field=models.CharField(blank=True, max_length=65, null=True, verbose_name='Причина отправки'),
        ),
    ]
