# Generated by Django 3.2.3 on 2022-02-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20220210_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record_block',
            name='date_add',
            field=models.DateField(verbose_name='Дата приема'),
        ),
    ]
