# Generated by Django 3.2.3 on 2022-02-18 09:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_record_block_date_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_processing',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_receipt',
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='amount_order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Получено'),
        ),
        migrations.AddField(
            model_name='order',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата заявки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='order',
            name='provider',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ожидает', 'ожидает'), ('обработан', 'обработан'), ('заказан', 'заказан'), ('получен', 'получен')], default='ожидает', max_length=25, null=True, verbose_name='Статус заявки'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.CharField(default=1, max_length=180, verbose_name='ФИО'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maker',
            name='maker_status',
            field=models.CharField(choices=[('ожидает', 'ожидает'), ('отправлен', 'отправлен'), ('возвращен', 'возвращен'), ('забракован', 'забракован')], default='отправлен', max_length=15, verbose_name='Состояние'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='component',
        ),
        migrations.AddField(
            model_name='order',
            name='component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='component_request', to='base.component', verbose_name='Наименование компонента'),
        ),
        migrations.AlterField(
            model_name='record_block',
            name='status',
            field=models.CharField(blank=True, choices=[('принят', 'принят'), ('готов', 'готов'), ('выдан', 'выдан'), ('забракован', 'забракован'), ('производителю', 'производителю')], default='принят', max_length=15, null=True, verbose_name='Состояние'),
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
