# Generated by Django 3.2.3 on 2022-02-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_record_block_date_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maker',
            name='maker_status',
            field=models.CharField(choices=[('ожидает', 'ожидает'), ('отправлен', 'отправлен'), ('возвращен', 'возвращен'), ('забракован', 'забракован')], default='отправлен', max_length=15, verbose_name='Состояние'),
        ),
    ]
