# Generated by Django 3.2.3 on 2022-02-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20220218_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_commit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Получено'),
        ),
        migrations.AlterField(
            model_name='component',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount_order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Заказано'),
        ),
    ]
