# Generated by Django 3.2.3 on 2022-02-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20220218_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created',
        ),
        migrations.AddField(
            model_name='order',
            name='date_commit',
            field=models.DateField(blank=True, null=True, verbose_name='Дата получения'),
        ),
        migrations.AddField(
            model_name='order',
            name='date_created',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заявки'),
        ),
        migrations.AddField(
            model_name='order',
            name='date_order',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='date_processing',
            field=models.DateField(blank=True, null=True, verbose_name='Дата обработки'),
        ),
    ]
