# Generated by Django 3.2.3 on 2022-02-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20220218_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Срок поставки'),
        ),
    ]
