# Generated by Django 3.2.3 on 2022-02-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_merge_20220221_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Срок поставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ожидает', 'ожидает'), ('обработан', 'обработан'), ('заказан', 'заказан'), ('получен', 'получен'), ('отменен', 'отменен')], default='ожидает', max_length=25, null=True, verbose_name='Статус заявки'),
        ),
    ]
