# Generated by Django 3.2.3 on 2022-02-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_order_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_amount',
            field=models.FloatField(null=True, verbose_name='Сумма счета'),
        ),
        migrations.AddField(
            model_name='order',
            name='payer',
            field=models.CharField(choices=[('ТРК', 'ТРК'), ('ВТС', 'ВТС'), ('ЭИС', 'ЭИС')], default='ожидает', max_length=25, null=True, verbose_name='Плательщик'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ожидает', 'ожидает'), ('обработан', 'обработан'), ('заказан', 'заказан'), ('получен', 'получен'), ('отменен', 'отменен'), ('недопоставка', 'недопоставка')], default='ожидает', max_length=25, null=True, verbose_name='Статус заявки'),
        ),
    ]
