# Generated by Django 3.2.3 on 2022-02-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20220221_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Сумма счета'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payer',
            field=models.CharField(blank=True, choices=[('ТРК', 'ТРК'), ('ВТС', 'ВТС'), ('ЭИС', 'ЭИС')], default='ожидает', max_length=25, null=True, verbose_name='Плательщик'),
        ),
    ]
