# Generated by Django 3.2.3 on 2022-02-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_auto_20220221_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payer',
            field=models.CharField(blank=True, choices=[('ТРК', 'ТРК'), ('ВТС', 'ВТС'), ('ЭИС', 'ЭИС'), ('--------', '--------')], default='--------', max_length=25, null=True, verbose_name='Плательщик'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ожидает', 'ожидает'), ('обработан', 'обработан'), ('заказан', 'заказан'), ('оплачен', 'оплачен'), ('получен', 'получен'), ('отменен', 'отменен'), ('недопоставка', 'недопоставка')], default='ожидает', max_length=25, null=True, verbose_name='Статус заявки'),
        ),
    ]
