# Generated by Django 3.2.3 on 2022-02-22 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20220218_1427'),
        ('base', '0026_auto_20220222_1108'),
    ]

    operations = [
    ]
