# Generated by Django 3.2.3 on 2022-03-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_auto_20220303_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_document',
            field=models.FileField(blank=True, null=True, upload_to='invoice_document_file/', verbose_name='Счет'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payer',
            field=models.CharField(blank=True, choices=[('ТРК', 'ТРК'), ('ВТС', 'ВТС'), ('ЭИС', 'ЭИС'), (None, '')], default=None, max_length=25, null=True, verbose_name='Плательщик'),
        ),
    ]
