# Generated by Django 3.2.3 on 2022-03-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_auto_20220315_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice_document',
            field=models.FileField(blank=True, null=True, upload_to='staticfiles/invoice_document_file/', verbose_name='Счет'),
        ),
    ]
