# Generated by Django 3.2.3 on 2022-03-23 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_alter_order_invoice_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purpose_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=30, verbose_name='Назначение')),
            ],
            options={
                'verbose_name': 'Назначение платежа',
                'verbose_name_plural': 'Назначение платежей',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='purpose_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.purpose_payment', verbose_name='Плательщик'),
        ),
    ]
