# Generated by Django 3.2.3 on 2022-03-23 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_auto_20220323_1034'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purpose_payment',
            new_name='Unit_payment',
        ),
        migrations.RenameField(
            model_name='unit_payment',
            old_name='purpose',
            new_name='unit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='purpose_order',
        ),
        migrations.AddField(
            model_name='order',
            name='unit_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.unit_payment', verbose_name='Подразделение'),
        ),
    ]
