# Generated by Django 3.2.3 on 2022-03-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_auto_20220323_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purpose_payment',
            name='purpose',
            field=models.CharField(max_length=30, unique=True, verbose_name='Назначение'),
        ),
        migrations.AlterField(
            model_name='unit_payment',
            name='unit',
            field=models.CharField(max_length=30, unique=True, verbose_name='Подразделение'),
        ),
    ]
