# Generated by Django 3.2.3 on 2022-03-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_auto_20220323_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maker',
            name='maker',
        ),
        migrations.RemoveField(
            model_name='maker',
            name='name_block',
        ),
        migrations.RemoveField(
            model_name='maker',
            name='number_block',
        ),
        migrations.RemoveField(
            model_name='maker',
            name='serial_number',
        ),
    ]
